### ISSUE TITLE
Notify => Service[apache2]

### ISSUE THREAD

**Issue by ayashjorden** [jamtur01/puppet-pagerduty#6]
Hello @jamtur01 
Was intended for those who install Puppet behind Apache2, right?

I've install Puppetserver(Java), so I need to send a 'refresh' event to puppet(server) services, correct?

Thank you,
Yarden

**Comment by jamtur01** [comment]
No - this is a standard report processor: https://docs.puppet.com/guides/reporting.html.

**Comment by jamtur01** [comment]
Probably? You can just ignore the manifest and just use the report processor.

**Comment by ayashjorden** [comment]
I don't follow, 
What do you mean by 'just ignore the manifest'? How the report processor will work w/o the API key configured?

I saw that pluginsync config is deprecated, removing it in my [fork](https://github.com/seekingalpha/puppet-pagerduty.git).

Also, can you examplify how to test it? will calling an undefined class will do ?

**Comment by jamtur01** [comment]
You just need a YAML file with the API key. See the template.

Regarding testing - I am not sure. Probably an undefined class will work.

**Comment by ayashjorden** [comment]
That is: install the module on the master and create the aforementioned YAML.

What about pluginsync?

**Comment by jamtur01** [comment]
@ayashjorden Sorry - I haven't used Puppet since before the puppetserver was released so I don't know how report processors are handled now but it's my understanding this just works by default now? https://docs.puppet.com/guides/plugins_in_modules.html#enabling-pluginsync

**Comment by ayashjorden** [comment]
Right :)
I'll test it today and hope to PR soon.

Thank you,
