### ISSUE TITLE
Report Keeps Triggering Incidents (PagerDuty)

### ISSUE THREAD

**Issue by ayashjorden** [jamtur01/puppet-pagerduty#7]
Hello,
The `process` method keeps triggering PD incidents even for `:incident_key => "puppet/#{self.host}"` that are already in 'TRIGGERED' status.

Will the `Redphone::Pagerduty.trigger_incident` method  trigger an incident even if the incident_key is assigned to an already triggered incident?

Shall I modify the report `process` method to query PD for the same incident_key before triggering an incident?

Thank you,
Yarden

**Comment by jamtur01** [comment]
There should already be a cache that does that from memory.

**Comment by ayashjorden** [comment]
Can you elaborate?

**Comment by jamtur01** [comment]
https://github.com/jamtur01/puppet-pagerduty/blob/master/lib/puppet/reports/pagerduty.rb#L50

**Comment by ayashjorden** [comment]
Working as expected,
Thank you
